-- AULA PARA APRENDER INSERT E LOOP NO TSQL.


-- DROP
DROP TABLE ALUNO;

-- CREATE 

CREATE TABLE ALUNO (
RM NUMBER(10),
NOME VARCHAR2(50), 
CONSTRAINT ALUNO_PK PRIMARY KEY(RM)
);

-- INSERT
INSERT INTO ALUNO (RM, NOME)VALUES (111222333, 'JOÃO');
INSERT INTO ALUNO (RM, NOME)VALUES (222333444, 'MARIA');
INSERT INTO ALUNO (RM, NOME)VALUES (333444555, 'JOSÉ');

--SELECT
SELECT * FROM ALUNO;

--UPDATE
UPDATE ALUNO
    SET NOME = 'PEDRO'
  WHERE RM = 333444555;
  
--INSERT
INSERT INTO ALUNO (RM, NOME) VALUES (444555666, 'JOSÉ');

--DELETE 
DELETE FROM ALUNO WHERE RM = 444555666;

--COMMIT
COMMIT;