SET SERVEROUTPUT ON
DECLARE
V_RM NUMBER(10) := 444555666;
V_NOME VARCHAR2(50) := 'DANIELA';
BEGIN 

UPDATE ALUNO
SET NOME = 'ALEX'
WHERE RM = V_RM;

DBMS_OUTPUT.PUT_LINE('O ALUNO COM RM: '||V_RM||' E '||V_NOME||' ATUALIZADO COM SUCESSO.');

COMMIT;

END;

-- UPDATE