    SET SERVEROUTPUT ON 
DECLARE
    V_RM NUMBER(10) := 444555666;
    V_NOME VARCHAR2(50) := 'DANIELA';
BEGIN

    INSERT INTO ALUNO(RM, NOME) VALUES (V_RM, V_NOME);
    
DBMS_OUTPUT.PUT_LINE('O ALUNO COM RM '||V_RM||' E '||V_NOME||' INCLUÍDO COM SUCESSO');

COMMIT;

END;

-- INSERT