SET SERVEROUTPUT ON
DECLARE
    V_IDADE NUMBER := &IDADE;
BEGIN
    IF V_IDADE <= 10 THEN
        DBMS_OUTPUT.PUT_LINE('CRIANCA');
    ELSIF V_IDADE <= 23 THEN
        DBMS_OUTPUT.PUT_LINE('JOVEM ADULTO');
    ELSE
        DBMS_OUTPUT.PUT_LINE('ADULTO');
    END IF;
END;
/
dd